apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.nginx.yml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: database
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: database
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.nginx.yml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/ocp-mean-stack-example-default: "true"
        io.kompose.service: database
    spec:
      containers:
        - env:
            - name: MONGO_DB
              value: mean-contacts
            - name: MONGO_DB_PASSWORD
              value: admin-password1
            - name: MONGO_DB_USERNAME
              value: admin-user1
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: admin-password
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin-user
          image: mongo:latest
          name: mean-mongo
          ports:
            - containerPort: 27017
              hostPort: 27017
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /home/mongodb
              name: database-claim0
            - mountPath: /docker-entrypoint-initdb.d
              name: database-claim1
            - mountPath: /data/db
              name: database-claim2
      restartPolicy: Always
      volumes:
        - name: database-claim0
          persistentVolumeClaim:
            claimName: database-claim0
        - name: database-claim1
          persistentVolumeClaim:
            claimName: database-claim1
        - name: database-claim2
          persistentVolumeClaim:
            claimName: database-claim2
status: {}
